version: '2'

services:
    web:
        image: nginx
        environment:
            - TERM=xterm
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.g/default.conf
            - .:/www
        ports:
            - "8080:80"
        links:
            - php

    php:
        image: tuxmate/php:5.5.9
        tty: true
        environment:
            - TERM=xterm
        volumes:
            - ./docker/php/www.conf:/etc/php5/fpm/pool.d/www.conf
            - ./docker/php/php.ini:/etc/php5/fpm/php.ini
            - .:/www
